bcgov/sso-requests

app/next.config.js
app/pages/index.tsx

- see https://nextjs.org/docs/api-reference/next.config.js/basepath

chore: fix the routing issue in github page

---

.github/workflows/terraform.yml
terraform/.terraform.lock.hcl
terraform/api-gateway.tf
terraform/lambda.tf
terraform/main.tf
terraform/rds.tf
terraform/variables.tf

add terraform to CI on dev pull requests

chore: terraform CI

---

terraform/lambda.tf
terraform/main.tf
terraform/rds.tf
terraform/variables.tf

use subnets from default vpc instead of new ones

fix: subnets

---

app/package.json
app/pages/_app.tsx
app/pages/request.tsx
app/schemas/form.ts
app/schemas/ui.ts
app/styles/globals.css
app/styles/request.module.css
app/yarn.lock

feat: form

---

app/schemas/form.ts

add oneof scenario for empty values in environments

fix: warning

---

app/__mocks__/axios.js
app/jest.config.js
app/jest/index.test.tsx
app/jest/mocks/styleMock.js
app/pages/_app.tsx
app/pages/index.tsx
app/pages/request.tsx
app/services/request.ts
app/tsconfig.json

add frontend service for request, baseUrl, and SPA links

chore: service

---

app/interfaces/form.ts
app/pages/request.tsx
app/services/request.ts

move ts import into required directory

fix: import

---

app/services/auth.ts
app/services/request.ts
lambda/app/src/authenticate.ts
lambda/app/src/main.ts

fix auth bugs in app and lambda

fix: auth in app

---

app/services/auth.ts
terraform/lambda-github.tf

gh_owner variable was missing
JSON parse was throwing error on empty string

fix: github

---

terraform/variables.tf

change audience to match the dev setup

fix: audience

---

terraform/variables.tf

recreate database to update naming

chore: re-run db

---

app/interfaces/utils.ts
app/pages/index.tsx
app/utils/openid.ts
lambda/app/src/authenticate.ts
lambda/app/src/routes.ts
lambda/github/src/main.ts

stringify json input for payload

fix: input format

---

lambda/actions/src/interfaces.ts
lambda/actions/src/main.ts

route handling for updating apply, plan, creation

chore: routes

---

lambda/actions/src/main.ts

test: auth

---

terraform/api-gateway.tf

redeploy api gateway when integrations update

fix: redeploy

---

app/.eslintrc
app/components/ArrayFieldTemplate.tsx
app/components/FormButtons.tsx
app/components/FormTemplate.tsx
app/schemas/providers.ts

frontend changes for page 2 of the form

feat: page 2

---

app/components/FormReview.tsx
lambda/app/src/__tests__/formatData.ts
lambda/app/src/helpers.ts
lambda/app/src/main.ts
lambda/app/src/routes/requests.ts
lambda/db/src/local.ts
lambda/db/src/migrations/2021.07.02T15.57.60.create-requests-table.ts
lambda/shared/interfaces.ts
lambda/shared/sequelize/models/Request.ts

update backend lambda with new fields

feat: backend update

---

app/services/request.ts
app/utils/helpers.ts

move rest args to fron of object to override with new values

fix: destructure

---

lambda/actions/src/main.ts
lambda/app/src/routes/requests.ts
lambda/db/src/local.ts
lambda/db/src/migrations/2021.07.01T15.57.60.create-requests-table.ts
lambda/shared/sequelize/models/Request.ts
terraform/variables.tf

add status handling for requests in actions handler

fix: status

---

app/form-components/FormStage.tsx
app/form-components/FormTemplate.tsx
app/schemas/providers.ts
app/schemas/urls.ts

change url format to custom pattern to support localhost

chore: pattern

---

app/interfaces/Request.ts
app/schemas/requester-info.ts
app/utils/helpers.ts

fix type mismatch of public access

fix: public access

---

app/styles/globals.css

inline radios with only two options, match field spacing to spec

chore: radios

---

app/form-components/FormReview.tsx
app/pages/_app.tsx
app/pages/my-requests.tsx

add success banner to my-requests page

chore: success banner

---

app/form-components/FormButtons.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/jest/form.test.tsx
app/jest/request.test.tsx
app/jest/utils/setup.ts
app/pages/request/[rid].tsx
app/styles/globals.css

test request page loading data, fix extra load when making a new form

test: request page

---

app/components/TermsAndConditions.tsx
app/form-components/ArrayFieldTemplate.tsx
app/form-components/FormButtons.tsx
app/form-components/FormHeader.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/layout/Layout.tsx
app/styles/globals.css
app/styles/theme.ts

small css tweaks around spacing

style: css

---

app/components/RequestInfoPanel.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/services/request.ts
lambda/.gitignore
lambda/app/Makefile
lambda/app/package.json
lambda/app/src/helpers.ts
lambda/app/src/routes/requests.ts
lambda/app/yarn.lock

add rjsf validations to backend when submitting

feat: vlaidations

---

lambda/actions/src/main.ts

return error for easier debugging

test: log error

---

app/schemas/urls.ts

title has to be empty string instead of null

fix: title

---

app/components/BottomAlertWrapper.tsx
app/components/PageLoader.tsx
app/components/TermsAndConditions.tsx
app/form-components/FormReview.tsx
app/form-components/GovForm.tsx
app/pages/_app.tsx
app/pages/my-requests.tsx
app/pages/request/[rid].tsx
app/schemas/providers.ts
app/schemas/requester-info.ts
app/styles/theme.ts
app/utils/helpers.ts
lambda/actions/src/main.ts

css tweaks, and a status check on backend lambda function

chore: styles

---

lambda/actions/src/main.ts
lambda/db/src/migrations/2021.07.02T15.57.60.create-events-table.ts
lambda/shared/sequelize/models/Event.ts
terraform/variables.tf

save tf plan information in the plan event

chore: plan

---

lambda/actions/src/actions/createEvent.ts
lambda/actions/src/actions/wakeUp.ts
lambda/actions/src/main.ts
terraform/api-gateway.tf

add heartbeat method for github actions lambda function

chore: heartbeat

---

app/form-components/ArrayFieldTemplate.tsx
app/form-components/GovForm.tsx
app/styles/globals.css

block level string fields, remove html5 validations

chore: style

---

app/form-components/FormTemplate.tsx
app/form-components/GovForm.tsx

move validation transforms to base form component

chore: validations

---

app/jest/helpers.test.ts
app/schemas/providers.ts
app/utils/helpers.ts

chore: remove github

---

app/schemas/shared/providers.ts

escape backslash character in input regex

fix: escape

---

.github/workflows/deploy-gh-pages.yml

add API url to the deploy script

fix: api url

---

app/form-components/FormHeader.tsx
app/form-components/FormTemplate.tsx
app/interfaces/form.ts
app/jest/form.test.tsx
app/services/request.ts
lambda/app/src/routes/requests.ts

block new submissions if a request exists in the apply failed state

feat: apply-failed error

---

lambda/__tests__/actions.test.ts
lambda/__tests__/jest.setup.js
lambda/jest.config.js
lambda/package.json
lambda/yarn.lock

tests for lambda actions function

test: actions

---

app/schemas/redirect-uris.ts
app/schemas/shared/providers.ts
app/utils/helpers.ts
app/utils/shared/customValidate.ts

don't show duplicate validations on URIs. Move message to array item level

fix: validations

---

app/components/InstallationPanel.tsx
app/components/RequestInfoTabs.tsx
app/form-components/FormButtons.tsx
app/html-components/Button.tsx
app/pages/my-requests.tsx
app/styles/theme.ts

style adjustments for the dashboard view

style: dashboard

---

app/components/InfoOverlay.tsx
app/components/RequestInfoTabs.tsx
app/form-components/ArrayFieldTemplate.tsx
app/form-components/FieldTemplateWithTitle.tsx
app/form-components/FormReview.tsx
app/jest/form.test.tsx
app/layout/Layout.tsx
app/pages/index.tsx
app/schemas/shared/providers.ts
app/schemas/shared/requester-info.ts
app/schemas/ui.ts
app/styles/globals.css
app/styles/theme.ts
app/utils/constants.ts
app/utils/helpers.ts
app/utils/widgetWrapper.tsx

frontend updates for application
- Add popover to ArrayField (make reusable component)
- Change notification messages
- rearrange form fields
- css tweaks

chore: updates

---

app/components/RequestInfoTabs.tsx
app/schemas/shared/requester-info.ts

make link external, text updates

chore: text

---

app/components/HelpText.tsx
app/components/RequestInfoTabs.tsx
app/components/SHeader3.tsx
app/components/SubmittedStatusIndicator.tsx
app/jest/statusIndicator.test.tsx
app/pages/my-requests.tsx
app/styles/theme.ts

feat: status

---

app/schemas/redirect-uris.ts
app/schemas/shared/providers.ts
app/schemas/shared/requester-info.ts
app/utils/widgetWrapper.tsx

limit client name to only 50 characters

chore: limit

---

lambda/app/src/routes/requests.ts
lambda/db/src/migrations/2021.08.20T15.57.60.update-requests-table.ts
lambda/shared/sequelize/models/Request.ts

add db migration for archived requests, update public_access default

chore: delete

---

lambda/app/src/main.ts
lambda/app/src/routes/requests.ts

delete wont take a body, add to query params

fix: query

---

docs/developer-guide.md

writeup a how-to-use doc for developers

docs: dev guide

---

app/index.d.ts
app/pages/_app.tsx
app/services/auth.ts
app/services/axios.ts
app/services/keycloak.ts
app/services/request.ts
app/utils/jwt.ts
app/utils/provider.ts

move config and refresh logic into axios interceptor

feat: axios interceptor

---

app/form-components/FormTemplate.tsx
app/jest/form.test.tsx
app/pages/admin-dashboard.tsx
app/pages/edit-request.tsx
app/services/axios.ts

routing buttons, fix heartbeat, ui

chore: dashboard

---

app/form-components/FormTemplate.tsx
app/pages/index.tsx
app/utils/constants.ts

leave button title as cancel on first page

fix: button title

---

lambda/app/src/routes/requests.ts

allow admin access to the getRequest and deleteRequest routes

chore: admin

---

app/form-components/FormReview.tsx
lambda/app/src/routes/requests.ts

fix where clause when deleting a request

fix: delete

---

app/form-components/FormTemplate.tsx
app/services/request.ts

handle clocking errors at service level for consistency

chore: messages

---

app/components/RequestPreview.tsx
app/components/SubmittedStatusIndicator.tsx
app/layout/Layout.tsx
app/pages/_app.tsx
app/pages/application-error.tsx
app/schemas/shared/requester-info.ts
lambda/shared/utils/templates.ts

update title, limit to two emails

chore: title

---

app/components/ActionButtons.tsx
app/components/EventContent.tsx
app/components/RequestInfoTabs.tsx
app/components/RequestTabs.tsx
app/pages/my-requests.tsx

add archived view to user view

chore: view archived

---

app/components/ActionButtons.tsx
app/components/UserEventPanel.tsx
app/form-components/FormTemplate.tsx
app/interfaces/Request.ts
app/pages/my-requests.tsx
app/services/event.ts
lambda/actions/src/actions/createEvent.ts
lambda/app/src/routes/events.ts
lambda/app/src/routes/requests.ts
lambda/app/src/utils/helpers.ts
lambda/db/src/migrations/2021.09.21T15.57.71.add-requester-notifications.ts
lambda/shared/sequelize/models/Request.ts

add notifications to user dashboard

chore: notifications

---

app/pages/index.tsx
app/services/auth.ts

chore: link

---

app/components/BceidStatus.tsx
app/components/RequestPreview.tsx
app/components/SHeader.tsx
app/components/StatusList.tsx
app/components/SubmittedStatusIndicator.tsx
app/form-components/BceidEmailTemplate.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/jest/form.test.tsx
app/pages/index.tsx
app/schemas/shared/providers.ts
app/schemas/shared/requester-info.ts
app/schemas/ui.ts
lambda/__tests__/actions.test.ts
lambda/__tests__/app.test.ts
lambda/app/src/__tests__/processRequest.test.ts
lambda/app/src/routes/requests.ts
lambda/app/src/utils/helpers.ts
lambda/shared/interfaces.ts

chore: bceid

---

lambda/app/src/keycloak/installation.ts

Fix kcadmin to use the correct realm and client id

fix: kcadmin

---

app/components/ConfigurationUrlPanel.tsx
app/services/keycloak.ts
lambda/app/src/keycloak/installation.ts
lambda/app/src/routes/installation.ts

fix return values and error handling for backend

fix: error handling

---

app/form-components/EnvironmentsFieldTemplate.tsx
app/interfaces/Request.ts
app/jest/form.test.tsx
app/schemas/shared/providers.ts
app/schemas/ui.ts
app/styles/globals.css
app/utils/helpers.tsx
lambda/app/src/__tests__/processRequest.test.ts
lambda/app/src/routes/requests.ts
lambda/app/src/utils/helpers.ts

chore: checkboxes

---

app/components/BceidStatus.tsx
app/components/InfoMessage.tsx
app/components/InstallationPanel.tsx
app/components/SubmittedStatusIndicator.tsx
docs/developer-guide.md

add info message for .well-known endpoints

chore: info message

---

lambda/app/src/routes/requests.ts
lambda/app/src/utils/helpers.ts
lambda/shared/utils/templates.ts

update email language and cc list for production bceid

chore: email

---

app/components/RequestInfoTabs.tsx
app/form-components/BceidEmailTemplate.tsx

remove bceid status for idir only requests

fix: bceid

---

app/components/RequestInfoTabs.tsx
app/pages/faq.tsx
app/pages/my-requests.tsx
app/pages/request/[rid].tsx
app/pages/terms-conditions.tsx
app/reducers/requestReducer.ts
app/schemas/redirect-uris.ts
app/services/auth.ts
app/utils/helpers.tsx
app/utils/jwt.ts
app/utils/shared/customValidate.ts
app/utils/widgetWrapper.tsx
lambda/__tests__/actions.test.ts
lambda/__tests__/app.test.ts
lambda/__tests__/db.test.ts
lambda/actions/src/actions/updateStatus.ts
lambda/actions/src/main.ts
lambda/app/src/authenticate.ts
lambda/app/src/github.ts
lambda/app/src/keycloak/client.ts
lambda/app/src/keycloak/installation.ts
lambda/app/src/main.ts
lambda/db/src/main.ts
lambda/db/src/umzug.ts
lambda/shared/sequelize/models/Event.ts
lambda/shared/sequelize/models/Request.ts

fix sonar code smells in codebase

chore: sonar

---

app/pages/index.tsx

update sla language on front page

chore: language

---

lambda/app/src/routes/requests.ts
lambda/shared/utils/templates.ts

add prefix to IDIM emails for env

chore: prefix

---

lambda/app/src/routes/requests.ts

remove production check if only in idir

fix: prod check

---

app/components/RequestInfoTabs.tsx
app/components/RequestTabs.tsx
app/components/SubmittedStatusIndicator.tsx
app/page-partials/admin-dashboard/AdminTabs.tsx
app/pages/_app.tsx
app/pages/admin-dashboard.tsx
app/pages/my-requests.tsx
app/utils/helpers.tsx
lambda/app/src/routes/requests.ts

add status indicator, approve handling

chore: bceid-approval

---

lambda/__tests__/app.test.ts
lambda/app/src/routes/requests.ts
lambda/db/src/migrations/2021.11.26T15.57.71.add-browser-flow-override.ts

add override to db and update function

chore: add override

---

lambda/shared/utils/templates.ts

make email change language more generic

fix: email

---

app/schemas/shared/providers.ts

relabel idir to idir and azure idir

chore: label

---

app/components/CenteredModal.tsx
app/form-components/AddTeamWidget.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/form-components/TeamFieldTemplate.tsx
app/form-components/TeamForm.tsx
app/interfaces/team.ts
app/schemas/non-bceid-schemas.ts
app/schemas/shared/requester-info.ts
app/schemas/ui.ts
app/services/axios.ts
app/services/request.ts
app/services/team.ts
app/utils/constants.ts
app/utils/helpers.tsx
lambda/__tests__/03.app.test.ts
lambda/app/src/__tests__/validate.test.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/routes.ts
lambda/app/src/utils/helpers.ts
lambda/db/src/migrations/2021.12.18T15.57.90.update-requests-table.ts
lambda/shared/interfaces.ts
lambda/shared/sequelize/models/Request.ts

hook up frontend to create and load teams from backend

feat: teams

---

app/components/CenteredModal.tsx
app/components/ErrorText.tsx
app/form-components/AddTeamWidget.tsx
app/form-components/FormTemplate.tsx
app/form-components/TeamForm.tsx
app/interfaces/Request.ts
app/package.json
app/pages/verify-user.tsx
app/utils/constants.ts
app/utils/helpers.tsx
app/utils/shared/customValidate.ts
app/yarn.lock
lambda/__tests__/02.request.test.ts
lambda/app/src/controllers/team.ts
lambda/app/src/utils/helpers.ts
lambda/shared/interfaces.ts
lambda/shared/utils/ches.ts
lambda/shared/utils/templates.ts

updates to email invitation and frontend error handling

chore: teams

---

.github/workflows/terraform.yml
terraform/lambda-app.tf
terraform/variables.tf

add API url envirnment variable

chore: env var

---

.github/workflows/terraform.yml
lambda/app/src/routes.ts

change to a valid redirection syntax

chore: redirect

---

lambda/db/src/migrations/2021.12.18T15.57.91.update-requests-table.ts

migration to change null uses_team values to false

chore: update

---

.github/workflows/test.yml
app/jest/helpers.test.ts
app/utils/shared/customValidate.ts

allow custm urls without http prefix

fix: custom URL

---

app/components/CenteredModal.tsx
app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/interfaces/team.ts
app/page-partials/my-requests/TeamInfoTabs.tsx
app/services/team.ts
lambda/__tests__/01.user-team.test.ts
lambda/app/src/controllers/team.ts
lambda/app/src/routes.ts

add permissions check for updating/reading a team

chore: permissions

---

app/components/CenteredModal.tsx
app/components/ConfigurationUrlPanel.tsx
app/components/InstallationPanel.tsx
app/components/TopAlertWrapper.tsx
app/form-components/FormReview.tsx
app/form-components/FormTemplate.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/html-components/FadingAlert.tsx
app/layout/Layout.tsx
app/layout/TopAlert.tsx
app/package.json
app/page-partials/my-requests/TeamInfoTabs.tsx
app/services/team.ts
app/utils/helpers.tsx
app/yarn.lock
lambda/app/src/controllers/team.ts
lambda/app/src/routes.ts

add functionality to delete team members

chore: delete user

---

app/components/CenteredModal.tsx
app/html-components/Table.tsx
app/jest/helpers.test.ts
app/page-partials/my-requests/TeamInfoTabs.tsx
app/styles/theme.ts
app/utils/helpers.tsx

- Export the type for button variants
- Add a 'mini' variant to the table component matching UI design
- Frontend function to verify user can delete a member
- Update the delete modal for members to handle allowed/not allowed cases
- Add an 'Integrations' Tab to the user panel with status icon indicators

feat: integration tab

---

lambda/__tests__/01.user-team.test.ts
lambda/__tests__/03.app.test.ts
lambda/app/src/controllers/team.ts

add verification and tests for deleting user permissions

feat: delete user api

---

app/page-partials/new-request/SolutionNavigator.tsx
app/schemas/shared/providers.ts

This PR:
removes the hover text explaining what a PCKE is
Updates the text on the solution explorer text

updated request forms text

---

app/components/ActionButtons.tsx
app/form-components/FormTemplate.tsx
app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/html-components/Table.tsx
app/interfaces/props.ts
app/page-partials/my-requests/ProjectTeamTabs.tsx
app/page-partials/my-requests/TeamInfoTabs.tsx
app/pages/admin-dashboard.tsx
app/pages/my-requests.tsx
app/styles/theme.ts
app/utils/helpers.tsx

- Update UserSession interface/name
- Pass current user through to team forms to allow a read only field of them as admin
- Minor style updates (spacing and capitalization)

fix: style

---

docs/developer-guide.md

add missing steps to the developer setup guide

fix: guide

---

app/components/ActionButtons.tsx
app/html-components/Table.tsx
app/pages/my-requests.tsx
app/pages/verify-user.tsx
app/styles/globals.css
docs/developer-guide.md
lambda/app/package.json
lambda/app/src/routes.ts
lambda/app/yarn.lock

CSS tweaks, error message change, fix for fetching archived requests

fix: teams

---

app/components/WarningModalContents.tsx
app/dispatchers/requestDispatcher.ts
app/form-components/FormTemplate.tsx
app/jest/formStage.test.tsx
app/page-partials/my-requests/ProjectTeamTabs.tsx
app/page-partials/my-requests/TeamInfoTabs.tsx
app/reducers/dashboardReducer.ts
app/services/team.ts
lambda/app/src/controllers/team.ts
lambda/app/src/routes.ts

- update delete api route to clear foreign key reference
- factor out warning styled modal contents
-

feat: delete team

---

app/page-partials/faq/FaqItems.tsx

add two extra questions to faq page

chore: add faq

---

app/pages/index.tsx

removed the duplicated FaqItems

chore: faq landing page

---

lambda/app/src/controllers/team.ts

add to logs to debug lambda issue in dev

chore: debug

---

README.md
app/components/ActionButtons.tsx
app/page-partials/my-requests/TeamInfoTabs.tsx
app/pages/my-requests.tsx
lambda/app/src/controllers/team.ts

- Move the view action button to first element
- add spacer above the integrations table
- Default loading to true to prevent render flash
- Explicitly set omitNull to false to allow teamId update

fix: delete team

---

app/page-partials/new-request/SolutionNavigator.tsx

feat: fixTypo

---

lambda/app/package.json
lambda/app/src/routes.ts
lambda/app/tsconfig.json
lambda/app/yarn.lock

- The issue might be coming from the different environments; local `ts-node` and lambda.
- see https://github.com/TypeStrong/ts-node/issues/1096#issuecomment-959454477

chore: fix an issue building encodeurl library

---

app/form-components/team-form/EditTeamNameForm.tsx

This fixes the on close feature

feat: fixcancle

---

lambda/app/src/controllers/installation.ts
lambda/app/src/routes.ts

- fix the bug blocking team members downloading installation json

fix: checks team members to allow json installation download

---

lambda/.gitignore
lambda/__tests__/__snapshots__/20.templates.test.ts.snap
lambda/__tests__/fixtures.ts
lambda/actions/Makefile
lambda/actions/package.json
lambda/actions/tsconfig.json
lambda/actions/yarn.lock
lambda/app/Makefile
lambda/app/package.json
lambda/app/src/controllers/requests.ts
lambda/app/src/queries/request.ts
lambda/app/tsconfig.json
lambda/app/yarn.lock
lambda/db/Makefile
lambda/db/src/migrations/2022.02.03T19.55.22.add-requester-in-request-table.ts
lambda/db/tsconfig.json
lambda/shared/interfaces.ts
lambda/shared/sequelize/models/Request.ts
lambda/shared/templates/bceid-request-approved/index.ts
lambda/shared/templates/bceid-request-approved/template.html
lambda/shared/templates/create-request-approved/index.ts
lambda/shared/templates/create-request-approved/template.html
lambda/shared/templates/create-request-submitted/template.html
lambda/shared/templates/helpers.ts
lambda/shared/templates/uri-change-request-approved/index.ts
lambda/shared/templates/uri-change-request-approved/template.html
lambda/shared/templates/uri-change-request-submitted/index.ts
lambda/shared/templates/uri-change-request-submitted/template.html

- in order to retrieve the requester info when the changes are applied, store the requester info into the db.
- copy html templates into lamda build artifacts as Typescript doesn't include them.

chore: pass the requester info to the github actions

---

app/components/RequestPreview.tsx
app/interfaces/Request.ts
app/page-partials/admin-dashboard/MetadataEditModal.tsx
app/schemas/shared/requester-info.ts
app/schemas/ui.ts
app/utils/helpers.tsx
lambda/app/package.json
lambda/app/src/controllers/requests.ts
lambda/app/src/queries/request.ts
lambda/app/src/utils/helpers.ts
lambda/app/yarn.lock
lambda/shared/sequelize/models/Request.ts
lambda/shared/sequelize/models/Team.ts

- update minor text title on the form page.
- allow reverting to select no team after creating an integration.
- use `pg-format` to avoid SQL injection.

chore: allow updating team selection in the form page

---

lambda/db/src/migrations/2022.02.10T09.52.22.convert-user-to-member.ts

data migration for the role display

fix: data migration

---

app/components/FloatingAlert.tsx
app/interfaces/team.ts
app/layout/Layout.tsx
app/layout/TopAlert.tsx
app/layout/UserProfileModal.tsx
app/pages/_app.tsx
app/services/user.ts
app/styles/globals.css
lambda/app/src/controllers/user.ts
lambda/app/src/routes.ts
lambda/db/src/migrations/2022.02.24T11.35.00.add-additional-email-in-user-table.ts
lambda/shared/sequelize/models/User.ts

- add user profile update modal

feat: add profile update modal

---

app/components/InstallationPanel.tsx

update the endpoint link in integration page

feat: linkError

---

app/form-components/FormTemplate.tsx
app/page-partials/my-dashboard/IntegrationList.tsx

update the wiki link from ocp-sso to sso-keycloak in create integration page

chore: wikiLink

---

app/utils/jwt.ts
lambda/app/src/authenticate.ts
lambda/app/src/routes.ts

- increase the grace period time to 8 hours to accept tokens

chore: increase grace period time to 8 hours when verifying token

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx
lambda/__tests__/01.user-team.test.ts
lambda/app/src/controllers/team.ts
lambda/app/src/queries/team.ts
lambda/app/src/routes.ts

- (997) allow users to see the teams only if they accepted the invitations in the email link.

chore: exclude teams that the user hasn't accept the invitation

---

app/components/Table.tsx
app/page-partials/my-dashboard/TeamInfoTabs.tsx
app/page-partials/my-dashboard/TeamList.tsx
app/pages/my-dashboard/teams.tsx
app/pages/verify-user.tsx
lambda/__tests__/04.auth.test.ts
lambda/app/src/queries/team.ts
lambda/app/src/routes.ts

- (976) prevent prompt team delete modal if not allowed to delete
- prevent table headers from flickering when loading data
- (1000) allow team deletion when team integrations are removed
- (996) hide add team member button if not admin
- (880) display different screens according to the token status

chore: bug fixes

---

app/form-components/FormTemplate.tsx
app/jest/form.test.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs.tsx
lambda/app/src/helpers/token.ts
lambda/app/src/routes.ts

- update text displaying request environments
- navigate to the first step when editing integrations
- handle token verification error from invitation link

chore: fix minor issues

---

app/form-components/FormTemplate.tsx
app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx

- https://trello.com/c/RO1prjhd/821-css-new-team-name-notification-banner-and-follows-integration-request

feat: prompt success notification when creating team

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx

add role info button to the right hand panel in team page

feat: add info button

---

app/layout/UserProfileModal.tsx

add info button for explainning additional email

feat: add info button for additional email

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx
app/styles/globals.css

feat: integration

---

app/components/InfoOverlay.tsx
app/form-components/ArrayFieldTemplate.tsx
app/form-components/FieldTemplate.tsx
app/interfaces/Request.ts
app/interfaces/form.ts
app/layout/UserProfileModal.tsx
app/page-partials/my-dashboard/TeamInfoTabs.tsx
app/schemas/environment-gold.ts
app/schemas/providers.ts
app/schemas/redirect-uris.ts
app/schemas/requester-info.ts
lambda/actions/tsconfig.json
lambda/app/src/github.ts
lambda/app/src/utils/helpers.ts
lambda/app/tsconfig.json
lambda/db/src/migrations/2022.04.06T16.00.00.add-roles-fields-in-request-table.ts
lambda/db/src/umzug.ts
lambda/db/tsconfig.json
lambda/scheduler/tsconfig.json
lambda/shared/sequelize/models/Request.ts
lambda/tsconfig.json
localserver/tsconfig.json
tsconfig.json

- add roles sections for gold integrations
- use `base typescript config` to share the common configs
- refactor `InfoOverlay` component take more options

feat: add roles section for an environment in gold

---

app/package.json
app/page-partials/my-dashboard/VerticalLayout.tsx
app/pages/my-dashboard/integrations.tsx
app/yarn.lock

- add a resizable vertical layout in projects page

feat: add vertical layout in project tab

---

app/components/RequestPreview.tsx

fixed the idp list display issue for reviewing and submitting an integration

feat: idpList empty

---

app/components/GenericModal.tsx
app/page-partials/my-dashboard/ClientRoles.tsx
app/page-partials/my-dashboard/roles/CreateRoleContent.tsx
lambda/app/src/keycloak/users.ts

In `Role Management` tab:
- highlight failed role creation items;
- show an option to retry.

feat: display failed role creation indication

---

app/components/GenericModal.tsx
app/page-partials/my-dashboard/ClientRoles.tsx
app/page-partials/my-dashboard/UserRoles.tsx

- fix `Generic Modal` issue that does not close.
- hide `IDIR Lookup tool` for IDP GUID search option.

chore: update minor ui logic

---

app/components/InfoOverlay.tsx
app/form-components/FieldAccessTokenLifespan.tsx
app/styles/globals.css

- fix typo
- add emailto button

ticket#1188/chore: add mailto button

---

app/components/InstallationPanel.tsx
app/components/RequestTabs.tsx
app/components/Table.tsx
app/page-partials/my-dashboard/ClientRoles.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs.tsx
app/page-partials/my-dashboard/UserRoles.tsx
app/page-partials/my-dashboard/VerticalLayout.tsx
lambda/app/src/controllers/requests.ts

- update the display of 20min integration processing layout
- update bottom panel title selection display
- some other minor UI fix, e.g. spacing
- update include features from ticket pVoMRB4f
- update include features from ticket 3EjK1gvo

chore: bottom panel UI fix

---

app/form-components/FieldAccessTokenLifespan.tsx

remove the email icon;
updated the info icon

chore: update info icon

---

.pre-commit-config.yaml
app/page-partials/my-dashboard/TeamInfoTabs.tsx
app/services/team.ts
docs/schema
lambda/app/src/controllers/team.ts
lambda/app/src/github.ts
lambda/app/src/queries/literals.ts
lambda/app/src/queries/request.ts
lambda/app/src/routes.ts
lambda/db/src/migrations/2022.05.30T11.59.00.add-sa-columns-in-request-table.ts
lambda/db/src/umzug.ts
lambda/shared/sequelize/models/Request.ts

- add team service account workflow

feat: support team service accounts

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx
app/schemas-ui/ui-gold.ts
lambda/app/src/controllers/team.ts
lambda/app/src/routes.ts

- set requester name when creating a service account.
- disable service account table from UI
- enable `Azure IDIR` option in gold

chore: minor updates

---

app/form-components/team-form/TeamMembersForm.tsx
app/html-components/Table.tsx
app/page-partials/my-dashboard/TeamInfoTabs.tsx

- add email validation header
- add gov email validation
- enable "delete" button when user is admin
- fix right hand panel column spacing
- fix read-only text alignment
- fix button alignment

chore: team UI fix

---

app/form-components/FormButtons.tsx
app/form-components/FormTemplate.tsx
app/form-components/SaveMessage.tsx
app/interfaces/form.ts
app/jest/form.test.tsx
app/jest/snapshots/__snapshots__/saveMessage.test.tsx.snap
app/jest/snapshots/saveMessage.test.tsx
app/page-partials/my-dashboard/UserRoles.tsx
app/services/keycloak.ts
lambda/app/src/keycloak/users.ts
lambda/app/src/routes.ts

- feat: throttle user roles updates
- chore: refactor `SaveMessage` component

feat: throttle user roles updates

---

.dockerignore
Dockerfile
docker-compose.yml
docs/developer-guide.md
localserver/nodemon-db.json
localserver/nodemon.example.json

Fixes https://trello.com/c/wDVjmuOa

Run the apps using docker compose

---

app/components/RequestPreview.tsx
app/components/SubmittedStatusIndicator.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs.tsx
app/page-partials/my-dashboard/IntegrationList.tsx

- move `submitted by` info location

chore: minor ui updates

---

app/jest/helpers.test.ts
app/utils/validate.ts

- update redirect URI rules to allow `-` and `.`

chore: update redirect uri rule

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx
lambda/actions/src/controllers/batch.ts
lambda/actions/src/routes.ts
lambda/app/src/controllers/team.ts
lambda/app/src/routes.ts
lambda/shared/enums.ts
lambda/shared/templates/helpers.ts
lambda/shared/templates/index.ts
lambda/shared/templates/team-api-service-account-created/index.ts
lambda/shared/templates/team-api-service-account-created/team-api-service-account-created.html
lambda/shared/templates/team-api-service-account-requested/index.ts
lambda/shared/templates/team-api-service-account-requested/team-api-service-account-requested.html
localserver/express-server.ts
localserver/tsconfig.json

Fixes 
https://trello.com/c/wSN32LUF/1233-css-api-account-ui-implementation
https://trello.com/c/Ygrl1DK6/1438-css-api-account-email-notification

CSS API Account Implementation and Email Notifications

---

terraform/env-resources.tf_dev
terraform/env-resources.tf_prod

- see https://www.terraform.io/language/settings/backends/s3#dynamodb-table-permissions for `S3 state locking`.

feat: create dynamodb for tf backend state locking

---

app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/page-partials/my-dashboard/TeamInfoTabs.tsx

- share the validation logic to validate team info.
- allow non-gov emails when inviting team members.

chore: allow non-gov emails when inviting team members

---

app/helpers/integration.ts
app/helpers/meta.ts
app/page-partials/my-dashboard/UserRoles.tsx
app/schemas-ui/ui-gold.ts
app/schemas/providers-gold.ts
lambda/app/package.json
lambda/app/src/main.ts
lambda/app/yarn.lock

- rename `github` to `githubbcgov`
- use `serverless-http` instead of custom code to build lambda backend in an express way.

chore: rename github to githubbcgov

---

lambda/__tests__/04.auth.test.ts
lambda/__tests__/base-event.json
lambda/app/src/main.ts
lambda/app/src/routes.ts
lambda/app/yarn.lock

- make use of `serverless-http`

Chore/rename GitHub

---

.tool-versions
docs/api-endpoints.md
lambda/__tests__/31.css-api.test.ts
lambda/css-api/k6-tests/load-tests.js
lambda/css-api/k6-tests/smoke-tests/modules/users.js
lambda/css-api/src/routes.ts
lambda/css-api/src/schemas/user.ts
lambda/css-api/src/services/user-service.ts
lambda/css-api/src/types.ts

Updated `firstName` to `name` and `lastName` to `loginid`

Updated GitHub endpoint query params

---

app/error-messages/e01.tsx
app/error-messages/e02.tsx
app/error-messages/e03.tsx
app/error-messages/e04.tsx
app/pages/application-error.tsx
app/services/axios.ts
app/svg/ErrorImage.tsx

- separate error templates out as the number grows
- handle 504 error in axios hook level

feat: add request time out error page

---

app/components/InstallationPanel.tsx
app/components/MessageBox.tsx
app/components/SubmittedStatusIndicator.tsx
app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
app/services/request.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/github.ts
lambda/app/src/routes.ts

- if has an error: show a red `Exclamation` icon with a message to reach out to the team.
- if taking too long without an error: show an `Info` icon with a resubmit button.
- otherwise, show nothing.

feat: support ability to re-submit requests if taking too long

---

app/.env.example
app/components/GithubDiscussions.tsx
app/jest/helpers.test.ts
app/utils/validate.ts

This adds more validation rules to the prod env

Uivalidation

---

.github/workflows/deploy-gh-pages-maintenance.yml

This has the correct conditional behaviour.

Maintenance action

---

app/schemas-ui/ui-gold.ts

This allows QA to change names in the dev environment

chore: temporarily enable name editing

---

app/next.config.js

Reverts bcgov/sso-requests#988

Revert "feat: add i18n locale into next.config"

---

app/pages/_app.tsx

Fixes [#SSOTEAM-636](https://bcdevex.atlassian.net/browse/SSOTEAM-636)

refactor: update session notification modal title and content 

---

lambda/scheduler/src/main.ts
terraform/lambda-scheduler.tf

[sso-675](https://bcdevex.atlassian.net/jira/software/projects/SSOTEAM/boards/39?selectedIssue=SSOTEAM-675)

chore: deactivate silver terraform batch job

---

app/jest/my-dashboard/my-projects/secrets.test.tsx
app/jest/snapshots/__snapshots__/pageLoader.test.tsx.snap
app/package.json
app/page-partials/my-dashboard/SecretsPanel.tsx
app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
app/yarn.lock

[SSOTEAM-705](https://bcdevex.atlassian.net/browse/SSOTEAM-705)

chore: update ui modals(secret tab and css api account tab) design to be same style

---

lambda/__tests__/06.email-templates.test.ts
lambda/__tests__/11.remove-inactive-users.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/__tests__/helpers/fixtures.ts
lambda/__tests__/helpers/modules/users.ts
lambda/app/src/controllers/user.ts
lambda/app/src/queries/team.ts
lambda/app/src/routes.ts
lambda/shared/enums.ts
lambda/shared/templates/delete-inactive-idir-users/delete-inactive-idir-users.html
lambda/shared/templates/delete-inactive-idir-users/index.ts
lambda/shared/templates/index.ts

Fixes [SSOTEAM-702](https://bcdevex.atlassian.net/browse/SSOTEAM-702)

feat: send emails to team that owns client used by inactive user

---

lambda/shared/utils/ches.ts
terraform/lambda-actions.tf

Fixes [SSOTEAM-773](https://bcdevex.atlassian.net/browse/SSOTEAM-773)

fix: pass realm registry api url to actions api

---

lambda/app/src/utils/helpers.ts

Testing to view the data passed to processRequest

fix: remove team id check

---

.bin/db-setup.sh
docs/developer-guide.md

[SSOTEAM-482](https://bcdevex.atlassian.net/jira/software/projects/SSOTEAM/boards/39?selectedIssue=SSOTEAM-482)

chore: update the docs and local env setup

---

app/components/ActionButtons.tsx
app/form-components/FieldTemplate.tsx
app/form-components/FormButtons.tsx
app/jest/form.test.tsx
app/page-partials/my-dashboard/IntegrationList.tsx
app/pages/admin-dashboard.tsx
app/pages/index.tsx

Adding some testids also changing existing `data-test-id`  to `data-testid` as per common convention.

feat: adding test ids for testing

---

README.md
docs/developer-guide.md

Documentation updates resulting from the work on https://bcdevex.atlassian.net/browse/SSOTEAM-977.

chore: updates to dev guide and readme ssoteam 977

---

app/page-partials/my-dashboard/UserRoles.tsx

fix backspace handling on multi-select component

fix: select backspace

---

lambda/__tests__/02.users-and-teams.test.ts
lambda/app/src/controllers/team.ts

fixes some bugs in the API logic to check if the user is the last admin on the team.

fix: remove user bug

---

lambda/actions/src/controllers/batch.ts

fix incorrect flag for adding vc email footer

fix: vc email

---

app/form-components/team-form/CreateTeamForm.tsx

fix: change maxlength to maxLength needs camelcase

---

terraform/env-resources.tf_dev

remove loki s3 bucket form dev env

chore: remove bucket

---

app/form-components/ArrayFieldTemplate.tsx

Adding a new testid for adding uris in the environment tabs.

feat: add test id for adding uris

---

app/helpers/integration.ts
app/utils/helpers.tsx

Remove DC from the installation JSON button title for production environment if not approved yet

chore: idp display

---

app/form-components/team-form/TeamMembersForm.tsx

Adding more test ids for the member management feature in teams.

feat: more test ids for the team functionality

---

app/components/TableNew.tsx
app/page-partials/my-dashboard/IntegrationList.tsx
app/page-partials/my-dashboard/TeamList.tsx

- Change table to optionally allow row selection to be controlled by parent
- Control row selection in Teams and Integrations table to allow default row selection

chore: row selection

---

app/services/request.ts

add optional string fields to list

fix: empty fields

---

app/form-components/team-form/EditTeamNameForm.tsx

The name edit modal does not have any testids adding for the name field and the 2 buttons.

feat: testid for the team name edit modal

---

app/page-partials/my-dashboard/TeamInfoTabs/index.tsx

Adding testids to the member table for a team. Added for the table and the 2 action buttons.

feat: test ids for the member table

---

app/form-components/FormTemplate.tsx

add dit email to confirm modal

chore: dit email

---

app/pages/_app.tsx
app/pages/faq.tsx
app/pages/index.tsx

It bothered me there was not a proper favicon shown.
Turned out that in the code it was misconfigured (wrong spots).
We have the bc favicon in the public directory, but it was not linked properly and in the wrong spots.
I've added: `<link rel="icon" href="/bcid-favicon-32x32.png" />` to `_app.tsx` and remove favicon references from `faq.tsx` and `index.tsx`.

fix: resolve favicon issues

---

app/form-components/team-form/TeamMembersForm.tsx

For description of the issue see here:
https://bcdevex.atlassian.net/browse/SSOTEAM-1193

fix: update validation ssoteam-1193

---

app/components/RequestPreview.tsx

See https://bcdevex.atlassian.net/browse/SSOTEAM-1196

fix: add readable idp names to request preview

---

app/components/InstallationPanel.tsx
app/form-components/FormTemplate.tsx
app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
app/page-partials/faq/FaqItems.tsx
app/schemas/providers.ts

updating some links. See ssoteam-789 for details

chore: links

---

app/components/RequestPreview.tsx
app/form-components/FormTemplate.tsx
app/interfaces/Request.ts
app/jest/form.test.tsx
app/jest/samples/integrations.ts
app/schemas-ui/ui-gold.ts
app/schemas/index.ts
app/schemas/requester-info.ts
app/services/request.ts
app/styles/globals.css
app/yarn.lock
lambda/__tests__/14.verifiable-credential.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/__tests__/helpers/fixtures.ts
lambda/actions/src/controllers/batch.ts
lambda/app/src/controllers/requests.ts
lambda/db/src/migrations/2023.11.09T15.37.58.add-primary-users.ts
lambda/db/src/umzug.ts
lambda/shared/sequelize/models/Request.ts
lambda/shared/templates/index.ts
lambda/shared/templates/integration-detail.html

- add question for primary end users
- Add new fields to database
- Update email templates to include in the details section

feat: users

---

app/services/request.ts

change from null to empty string for default val

chore: default val

---

app/page-partials/my-dashboard/RoleManagement/index.tsx

Added Test Ids for the "Create New Role" Button and the Modal that belongs to that functionality.

feat: add testids for roles testing

---

app/components/GenericModal.tsx
app/page-partials/my-dashboard/RoleManagement/index.tsx

A few more testid tweaks to improve testability.

feat: adding more testids for roles testing

---

app/page-partials/my-dashboard/UserRoles.tsx

Addition to support the search functions

feat: testids-for-user-role-select

---

lambda/shared/templates/index.ts

chore: format

---

.github/workflows/deploy-gh-pages-maintenance.yml

include dc env var in other deploy script

chore: var

---

.github/workflows/check-labels.yaml
.github/workflows/lint-pr.yml

add action to catch missing labels

chore: label action

---

app/schemas/providers.ts
lambda/__tests__/07.emails-for-user-requests.test.ts
lambda/__tests__/08.emails-for-team-requests.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/actions/src/controllers/batch.ts
lambda/shared/templates/bceid-warning.html
lambda/shared/templates/create-integration-applied/create-integration-applied.html
lambda/shared/templates/create-integration-applied/index.ts
lambda/shared/templates/index.ts
lambda/shared/templates/update-integration-applied/index.ts
lambda/shared/templates/update-integration-applied/update-integration-applied.html

Adding a note about one app per client. Added it above the redirect URIs and to the BCeID emails

chore: messaging

---

app/jest/integrationTabs.test.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx

Fix the DC flag to include case of no IDPs, e.g service accounts. Add test to catch potential bug in CI

fix: missing tab

---

lambda/__tests__/02.users-and-teams.test.ts
lambda/app/src/controllers/user.ts

Fixing case where user's email changes and GUID is the same breaking the unique email constraint.

chore: duplicated user

---

app/pages/admin-dashboard.tsx
lambda/app/src/controllers/requests.ts
lambda/app/src/keycloak/integration.ts

1. Handle client id update for SAML integrations
2. Set login theme for SAML integrations
3. Enable restore only for integrations with Applied and Deleted/Archived statuses

fix: minor tweaks

---

lambda/__tests__/06.email-templates.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/shared/templates/create-integration-applied/index.ts
lambda/shared/templates/create-integration-submitted/index.ts
lambda/shared/templates/create-team-api-account-approved/index.ts
lambda/shared/templates/create-team-api-account-submitted/index.ts
lambda/shared/templates/update-integration-applied/index.ts
lambda/shared/templates/update-integration-submitted/index.ts

Fixes [SSOTEAM-1399](https://bcdevex.atlassian.net/browse/SSOTEAM-1399)

feat: added numbering to emails

---

app/components/InstallationPanel.tsx
app/form-components/FormTemplate.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/jest/home.test.tsx
app/jest/layout.test.tsx
app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
app/jest/my-dashboard/my-projects/integrationList.test.tsx
app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
app/jest/my-dashboard/my-teams/cssApiAccount.test.tsx
app/jest/my-dashboard/my-teams/members.test.tsx
app/jest/my-dashboard/my-teams/teamList.test.tsx
app/layout/Layout.tsx
app/page-partials/faq/FaqItems.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
app/page-partials/my-dashboard/IntegrationList.tsx
app/page-partials/my-dashboard/ServiceAccountRoles.tsx
app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
app/page-partials/terms-conditions/Content.tsx
app/pages/index.tsx
app/pages/my-dashboard/s2g.tsx
app/schemas/providers-gold.ts
app/schemas/providers.ts
app/utils/constants.ts

Switch wiki to devhub, use constant for baseURL to prevent doing this again

chore: wiki links

---

app/form-components/team-form/TeamMembersForm.tsx
app/jest/my-dashboard/my-teams/members.test.tsx
app/jest/my-dashboard/my-teams/teamList.test.tsx
lambda/__tests__/06.email-templates.test.ts
lambda/__tests__/09.emails-for-teams.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/app/src/utils/helpers.ts
lambda/shared/templates/index.ts
lambda/shared/templates/team-invitation/index.ts
lambda/shared/templates/team-invitation/team-invitation.html

Update email body and tests (snapshots). Updated the team roles link to a more appropriate section of the docs.

chore: update invite email

---

lambda/app/src/controllers/requests.ts

remove disabling from delete route

fix: disabling

---

lambda/__tests__/03.requests-by-users.test.ts
lambda/app/src/controllers/requests.ts
lambda/shared/enums.ts

chore: events for restoration

---

lambda/app/src/controllers/requests.ts
lambda/request-monitor/Makefile
lambda/request-monitor/package.json
lambda/request-monitor/src/main.ts
lambda/shared/templates/restore-integration/index.ts
lambda/shared/templates/restore-integration/restore-integration.html

1. Request Monitor: Updated notification header prefix
2. Integration Restore Email: Additional Text to let clients know about secret update

feat: minor tweaks to email and rc notification

---

app/helpers/meta.ts
app/schemas/providers-gold.ts

Text changes for azure idir description

chore: change azure idir to idir with mfa

---

app/schemas/providers-gold.ts

update anchor for wiki link on idir with mfa

chore: change docs link

---

app/utils/openid.ts
app/utils/provider.ts

Fixes [SSOTEAM-1477](https://bcdevex.atlassian.net/browse/SSOTEAM-1477)

fix: populate openid configuration from sso_url

---

app/components/Carousel.tsx
app/components/Testimonial.tsx
app/interfaces/Testimonial.ts
app/jest/home.test.tsx
app/pages/index.tsx
app/utils/constants.ts

Some requested changes after review:
- Add a quote to the main page, 
- move testimonials beneath "what's new" 
- Remove FAQ from main page
- Use initials instead of full name
- Add titles to testimonials

chore: top quote on main page

---

lambda/css-api/src/services/role-service.ts

Fixes [https://bcdevex.atlassian.net/browse/SSOTEAM-1503](SSOTEAM-1503)

feat: keep existing composite roles

---

.github/workflows/e2e-smoke-test.yaml

New Action for kicking off the main-e2e test as a smoke test.

feat: ssoteam-1470 E2E Smoke Test at merge in dev

---

app/form-components/FormTemplate.tsx
app/schemas/providers-gold.ts

Fixes [SSOTEAM-1522](https://bcdevex.atlassian.net/browse/SSOTEAM-1522)

fix: saml - override roles attribute instead of adding new

---

app/form-components/team-form/TeamMembersForm.tsx
app/jest/home.test.tsx
app/jest/layout.test.tsx
app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
app/jest/my-dashboard/my-projects/integrationList.test.tsx
app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
app/jest/my-dashboard/my-teams/members.test.tsx
app/jest/my-dashboard/my-teams/teamList.test.tsx
app/layout/Layout.tsx
app/page-partials/faq/FaqItems.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
app/page-partials/my-dashboard/IntegrationList.tsx
app/page-partials/my-dashboard/ServiceAccountRoles.tsx
app/page-partials/terms-conditions/Content.tsx
app/pages/index.tsx
app/pages/my-dashboard/s2g.tsx
app/schemas/providers-gold.ts
app/utils/constants.ts
app/utils/text.ts

Adding query string to all wiki urls for user info scraping

chore: url

---

lambda/app/src/controllers/logs.ts

change line limit in sandbox (loki capped at 5000)

chore: dev limit

---

app/pages/admin-reports.tsx
lambda/app/src/controllers/reports.ts

fix events download to respect rds limit

feat: download events

---

app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx

- Add default dates
- Disable form fields while loading
- Abort API request and reset form if integration changes

chore: abort query

---

app/form-components/team-form/TeamMembersForm.tsx
app/form-components/widgets/MinutesToSeconds.tsx
app/jest/form.test.tsx
app/jest/samples/integrations.ts
app/schemas-ui/ui-gold.ts
app/schemas/environment-gold.ts
app/utils/constants.ts
app/utils/validate.ts

add error mesage for client idle/max. I Made a custom widget for it, I was going to try to make something more generic but since it has to display in minutes and emit in seconds the logic seemed too customized for that.

chore: client session form validations

---

.github/workflows/e2e.yaml

- Run ci test suite
- Change ref to main branch

chore: change e2e ref and test set

---

.github/workflows/zap-scan.yaml

Adding APP and API Scan - Just top level scan.

feat:  ssoteam 1371 owasp zap scan

---

app/pages/admin-dashboard.tsx

add more descriptive prompt for restoration user assignment

chore: prompt text

---

app/components/GithubDiscussions.tsx
app/form-components/FormTemplate.tsx
app/form-components/team-form/EditTeamNameForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/page-partials/my-dashboard/ServiceAccountRoles.tsx
app/page-partials/my-dashboard/TeamList.tsx
app/page-partials/my-dashboard/UserRoles.tsx
app/page-partials/my-dashboard/users-roles/IdimLookup.tsx
app/pages/admin-dashboard.tsx
app/utils/users.ts

add error handling to more ajax calls

chore: error handling

---

.github/workflows/e2e.yaml
local/terraform/main.tf

chore: update migrator

---

lambda/app/src/controllers/requests.ts

use client stopper for dc idps

chore: client stopper

---

lambda/__tests__/14.verifiable-credential.test.ts
lambda/app/src/controllers/requests.ts
lambda/shared/templates/create-integration-applied/index.ts
lambda/shared/templates/update-integration-applied/index.ts

chore: emails

---

app/form-components/FormTemplate.tsx
app/jest.setup.js
app/jest/form.test.tsx
app/schemas-ui/ui-gold.ts
app/utils/validate.ts
lambda/__tests__/14.verifiable-credential.test.ts

Until handling passing along the pres_req_conf_id on saml integrations is figured out we are disallowing it in the CSS app

chore: disable dc for saml

---

app/components/DeleteModal.tsx

await confirmation for loader display logic

fix: loader

---

app/components/DeleteModal.tsx

chore: deletion label

---

app/components/DeleteModal.tsx

Trim whitespace when doing comparison (UX request from tian)

chore: trim project name

---

.github/workflows/deploy-gh-pages.yml
.github/workflows/terraform.yml

enable dc in the production environment (and test)

chore: enable dc

---

app/form-components/ArrayFieldTemplate.tsx
app/jest/form.test.tsx
app/jest/helpers.test.ts
app/package.json
app/utils/validate.ts
app/yarn.lock
terraform/ecs.tf
terraform/roles.tf

…test (#1200)
* feat: dev and test, * not allowed in redirect URIs
* feat: update redirect URI unit test
* feat: added count to ecs_sso_grafana_task_execution_role
* feat: added index to ecs_sso_grafana_task_execution_role
* feat: fix terraform issues with indexes

feat: allow only fully qualified domains in redirect URI for dev and test

---

app/page-partials/terms-conditions/Content.tsx

chore: terms and condition text

---

app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx

Includes a modal for the logs download for clearer UI

feat: logs ui

---

app/schemas/providers-gold.ts
lambda/__tests__/11.remove-inactive-users.test.ts
lambda/app/src/controllers/user.ts
lambda/shared/enums.ts
lambda/shared/templates/index.ts
lambda/shared/templates/orphan-integration/index.ts
lambda/shared/templates/orphan-integration/orphan-integration.html

chore: deploy test

---

lambda/app/src/keycloak/integration.ts

correctly concat arrays, forgot that concat does not mutate unlike push in js

fix: scopes

---

app/page-partials/admin-dashboard/AdminTabs/BcServicesCardTabContent.tsx
app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
lambda/app/src/controllers/requests.ts
lambda/app/src/keycloak/idp.ts
lambda/app/src/keycloak/integration.ts
lambda/db/src/migrations/2024.06.21T11.35.24.add-bcsc-prod-approved.ts
lambda/db/src/umzug.ts
lambda/shared/sequelize/models/Request.ts

- Add in the post broker login flow and first broker login flow to idp creation
- Add in the production approval process and emails for bcsc

fix: idp login flows and prod approval

---

lambda/app/src/controllers/requests.ts

chore: display name

---

lambda/__tests__/20.bcsc.test.ts
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/utils/helpers.ts

add address to claims when requesting address scoped claims

fix: address

---

lambda/__tests__/20.bcsc.test.ts
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/utils/helpers.ts

* fix: address
add address to claims when requesting address scoped claims
* chore: sub
always request sub for stability

chore: release

---

app/schemas-ui/ui-gold.ts
app/schemas/providers-gold.ts

Add tooltip for SAML connections and fix typo in another tooltip. For the saml info it links out  [here](https://bcgov.github.io/sso-docs/integrating-your-application/saml).

chore: tooltips

---

app/page-partials/my-dashboard/UserRoles.tsx

add testid to table for easier selecting. Wrapped the table in a div since the component is using a fragment

chore: testid

---

app/page-partials/my-dashboard/users-roles/IdimLookup.tsx

update username form value to match ms graph

chore: username value

---

app/form-components/FieldTemplate.tsx
app/form-components/widgets/SwitchWidget.tsx
app/jest/form.test.tsx
app/schemas-ui/ui-gold.ts
app/schemas/requester-info.ts

Switch the usesTeam and projectLead to toggles and add reasonable defaults

feat: default values team

---

app/form-components/widgets/TooltipCheckboxesWidget.tsx
app/schemas/providers-gold.ts
app/styles/globals.css

Add a message about role assignment, fix padding on error messages. Looks like below:
And left aligning error messages:

feat: role message

---

terraform/lambda-app.tf
terraform/variables.tf

add var to terraform lambda function

fix: terraform var

---

.github/workflows/terraform.yml

add to missing auto.tfvars piece

chore: add flag to tf vars

---

lambda/__tests__/20.bcsc.test.ts
lambda/app/src/keycloak/integration.ts

fix environment check for bcsc scope

fix: bcsc-scope

---

.github/workflows/deploy-gh-pages-maintenance.yml
.github/workflows/deploy-gh-pages.yml

lock in github pages deploy patch version

chore: set action version

---

.github/workflows/e2e-keycloak.yaml
.github/workflows/e2e.yaml
app/cypress/e2e/ci/smoke-10-brokenlinks.cy.ts

Remove recording in cypress cloud and save artifacts in github action storage instead

chore: remove cypress cloud runs

---

.github/workflows/e2e.yaml

fix: actions

---

.github/workflows/e2e-keycloak.yaml
.github/workflows/e2e.yaml

comment out videos for now, leave code in case we add again

chore: disable videos

---

lambda/__tests__/15.sso-logs.test.ts
lambda/app/src/controllers/logs.ts
lambda/app/src/routes.ts
lambda/css-api/src/routes.ts
lambda/css-api/src/swagger.js

Add logs download feature to CSS API

feat: log download

---

docker-compose.yml

update bcsc vars for docker-compose setup

chore: local bcsc vars

---

app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
lambda/__tests__/17.run-queued-requests.test.ts
lambda/__tests__/helpers/modules/integrations.ts
lambda/db/src/migrations/2024.12.03T10.55.55.request-queue-attempts-column.ts
lambda/db/src/umzug.ts
lambda/request-queue/package.json
lambda/request-queue/src/main.ts
lambda/shared/sequelize/models/RequestQueue.ts
terraform/lambda-request-queue.tf

- added a clearer message for the log download rate limit on frontend
- add a backoff limit to the request queue

chore: backoff limit

---

app/page-partials/terms-conditions/Content.tsx
app/pages/index.tsx
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/shared/templates/sso-updates-mailing-list-message.html

update mailing list subscription link

chore: mailing list

---

app/jest/form.test.tsx
app/schemas-ui/ui-gold.ts
lambda/app/src/keycloak/integration.ts

disable bcsc removal for non admins

chore: disable bcsc

---

app/components/Table.tsx
app/jest/form.test.tsx
app/jest/ssoDashboard.test.tsx
app/page-partials/terms-conditions/Content.tsx
app/pages/admin-dashboard.tsx
app/pages/index.tsx
app/schemas-ui/ui-gold.ts
lambda/__tests__/21.requests-validations.test.ts
lambda/__tests__/24.bcsc-api.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/keycloak/integration.ts
lambda/app/src/queries/bcsc-client.ts
lambda/shared/templates/sso-updates-mailing-list-message.html
terraform/env-resources.tf_prod

chore: release test

---

app/cypress/pageObjects/requestPage.ts

Grab by label instead of internal ids for environments

fix: selectors

---

terraform/lambda-app.tf
terraform/lambda-request-queue.tf

add bcsc signature variable to lambda functions

chore: sig variable

---

lambda/__tests__/06.email-templates.test.ts
lambda/__tests__/07.emails-for-user-requests.test.ts
lambda/__tests__/08.emails-for-team-requests.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/__tests__/helpers/common-mocks.js
lambda/__tests__/helpers/fixtures.ts
lambda/app/src/controllers/requests.ts
lambda/package.json
lambda/shared/templates/update-integration-applied/index.ts
lambda/shared/templates/update-integration-applied/update-integration-applied.html
lambda/shared/templates/update-integration-submitted/index.ts
lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
lambda/shared/utils/ches.ts
lambda/yarn.lock

include changes in update emails

chore: email diff

---

lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/shared/templates/update-integration-applied/update-integration-applied.html
lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
lambda/shared/utils/ches.ts

add spacing and change phrasing on change emails

chore: email format

---

lambda/shared/utils/ches.ts

remove mapping on bcsc attributes

fix: bcsc attributes

---

.github/workflows/e2e.yaml
local/terraform/main.tf

update modules with new idp config

chore: tf modules

---

app/interfaces/Request.ts
app/jest/filters.test.tsx
app/utils/helpers.tsx

add social to admin dashboard filter and unit test

chore: admin filters

---

app/cypress/e2e/ci/integrations-crud.cy.ts
app/cypress/fixtures/requests.json
app/cypress/pageObjects/dashboardPage.ts
app/cypress/pageObjects/requestPage.ts
docker-compose.yml

add e2e test for social providers

test: e2e social

---

.github/workflows/deploy-gh-pages-maintenance.yml

include dc in the maitenance mode deploy

chore: add dc

---

lambda/app/package.json

copy the assessment form attachment for emails into the lambda function build

chore: attachment in build

---

lambda/__tests__/25.idp-approver.test.ts
lambda/app/src/queries/request.ts

- Update approver sequelize to match regular user for the unassigned teams case

chore: approver delete

---

app/.env.example
lambda/__tests__/10.team-api-account.test.ts
lambda/css-api/k6-tests/load-tests.js
lambda/css-api/k6-tests/smoke-tests/modules/users.js
lambda/css-api/src/controllers/user-controller.ts
lambda/css-api/src/routes.ts
lambda/css-api/src/schemas/user.ts
lambda/css-api/src/services/keycloak-service.ts
lambda/css-api/src/services/user-service.ts
lambda/css-api/src/swagger.js
lambda/css-api/src/types.ts

- Deprecated old BCeID search endpoints
- New one single endpoint to fetch all types of BCeID users
- Smoke and load tests updated

feat: latest endpoint for fetching bceid users for an integration

---

.github/workflows/deploy-gh-pages-maintenance.yml

fix dc variable on main branch

chore: include dc

---

app/page-partials/my-dashboard/TeamList.tsx

use passed variable to avoid stale state issue (activeTeam state not yet updated)

fix: stale data

---

lambda/__tests__/02.users-and-teams.test.ts
lambda/__tests__/helpers/modules/teams.ts
lambda/app/src/controllers/team.ts

Team role update route was returning the logged in user, not the updated user, causing UI bug. Updated and added unit tests for role update route

fix: team member roles

---

app/shared/templates/remove-inactive-idir-user-from-team/index.ts

switch to new template import syntax

fix: email template

---

app/jest-api/18.request-monitor.test.ts
app/queries/request.ts

exclude draft and failed integrations from active list

fix: active integrations

---

.github/workflows/e2e.yaml
app/cypress/appActions/Request.ts
app/cypress/e2e/ci/integrations-crud.cy.ts
app/cypress/fixtures/requests.json
app/cypress/pageObjects/dashboardPage.ts
docker-compose.yml

add e2e test for otp client crud

chore: otp e2e

---

helm/values-b29129-dev.yaml

update url displayed in swagger

chore: api url

---

app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
app/utils/helpers.ts

The copy/download otp prod JSON was showing when prod is not yet approved and available. Update to only show after production approval for OTP

fix: otp prod

---

.github/workflows/publish-image.yaml

Fix tag reference in deployment pipeline

chore: tag reference
