app/services/axios.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/routes.ts
lambda/shared/interfaces.ts
lambda/shared/templates/helpers.ts

- check if `request` data is `Sequelize` object to convert it to a plain object.
- refactor `update`, `delete` controller logic to follow the convention of `Sequelize` usages.

chore: refactor backend update, delete logic

---

app/layout/Layout.tsx
app/page-partials/faq/FaqItems.tsx
app/pages/index.tsx

update all WiKi page reference link in CSS home page, from opc-sso/wiki to sso-keycloak/wiki

feat: reference link

---

lambda/__tests__/03.app.test.ts
lambda/__tests__/04.auth.test.ts
lambda/app/src/main.ts
lambda/app/src/routes.ts

- mock `lambda-api-router` implementation to mimic its behaviours close to `Express.js`

chore: refactor backend routes to mimic expressjs behaviours

---

app/page-partials/my-dashboard/TeamInfoTabs.tsx
lambda/app/src/controllers/team.ts

Currently the PR number is undefined and this change shall fix it. Also the `CSS API Account` tab is selected by default if logged in user is an admin and service type is `gold`

Fixed issue with undefined PR number

---

app/page-partials/my-dashboard/UserRoles.tsx

fix the missing scenario by clicking the `X` button on the multi-selection.

chore: fix bug when clearning all roles

---

app/page-partials/admin-dashboard/AdminTabs/BceidTabContent.tsx
app/page-partials/admin-dashboard/AdminTabs/GithubTabContent.tsx
app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx

- When BCeID prod is approved and TF is active, the GitHub approve button is disabled
- When GitHub prod is approved and TF is active, the BCeID approve button is disabled

Updated Prod IDP Approval Flow

---

app/jest/snapshots/__snapshots__/saveMessage.test.tsx.snap
app/package.json
app/yarn.lock

The vulnerabilities reported by dependabot for the [sso-react-components](https://github.com/bcgov/sso-react-components) have been fixed in the version `1.28.6`. Using this version in our CSS APP

chore: using common components 1.28.6

---

app/form-components/FormTemplate.tsx
app/schemas-ui/ui-gold.ts
app/schemas/requester-info.ts
app/utils/validate.ts
lambda/app/src/utils/helpers.ts

1. Allow users to update project lead if integration is in draft state
2. Remove team id if creating a non team integration before submitting the request
3. Update report to include requester as admin if selecting team integration

fix: form issues with submitting integration updates of team and project lead

---

app/components/SurveyBox.tsx
app/form-components/FormTemplate.tsx
app/interfaces/Survey.ts
app/interfaces/team.ts
app/page-partials/my-dashboard/RoleManagement/index.tsx
app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
app/page-partials/my-dashboard/UserRoles.tsx
app/pages/_app.tsx
app/services/user.ts
lambda/__tests__/12.submit-survey.test.ts
lambda/__tests__/13.profile.test.ts
lambda/__tests__/helpers/modules/users.ts
lambda/app/src/controllers/user.ts
lambda/app/src/routes.ts
lambda/db/src/migrations/2023.10.11T15.12.25.add-user-surveys.ts
lambda/db/src/umzug.ts
lambda/shared/enums.ts
lambda/shared/interfaces.ts
lambda/shared/sequelize/models/Survey.ts
lambda/shared/sequelize/models/User.ts
lambda/shared/sequelize/models/models.ts
lambda/shared/templates/index.ts
lambda/shared/templates/survey-completed-notification/index.ts
lambda/shared/templates/survey-completed-notification/survey-completed-notification.html
localserver/express-server.ts
localserver/package.json
localserver/yarn.lock

Add in the survey component. The sonarcloud failure is on duplication between the umzug migration file and the sequelize model definition, which are in sync right now since the table is brand new, but should not be logically linked since the model will update over time but the migration is static. Some design decisions:
- I made the survey opening available globally from `_app.tsx`, I think this makes sense since it can be prompted throughout the app and only one survey componenet should ever render at a time
- Added the "has user been prompted" to the profile as a json object, seemed like the appropriate place for it
- Surveys as a new table
- Not notifying frontend users if the survey fails to send, these will be in our API logs and figure it would just annoy users to get an error …

feat: Survey Frontend

---

app/components/SurveyBox.tsx

Give the survey a z-index to keep in front of the select menu if open. 10 is enough to be in front of the select, checking the delete modal it is using 1000 so this will keep the survey behind modals if open

fix: survey

---

app/components/RequestPreview.tsx

In order to streamline the verification of the data in the preview tab, I have updated the RequestPreview.tsx as follows:
- I have added another parameter (testid) to the FormattedList function
```typescript
interface FormattedListProps {
list?: any[];
title: string;
inline?: boolean;
testid: string;
}
const FormattedList = ({ list, title, inline = false , testid }: FormattedListProps) => {
return (
<>
<tr>
<td>{title}</td>
{(list?.length === 1 || inline) && (
<SemiBold data-testid={testid}>
{list?.map((item, i) => (
<span key={item}>
{item}
{i !== list.length - 1 && ', '}{' '}
</span>
))}
</SemiBold>
)}
</tr>
```
- I now insert this testid into the span.
- Lines 145-153 contain the calls ```<FormattedList list={idpDisplay} title="Identity Providers Required:" inline …
```

feat: addition of new test Ids in the preview window

---

.github/workflows/terraform.yml
app/jest/form.test.tsx

Added some cleanup to this old test case, the clearer names you added Roland are a great idea, I did the same for the boxes. It was broken before because the whole naming off of indexes instead of names was making the wrong box be selected in some cases. I think some of the tests seemed to only be working by coincidence, and after you added in proper selection they were breaking. The tests are much clearer now where they are clicking.
I also added some small changes to reduce console noise, mocking a module that was throwing errors and adding in some `waitFor` in test cases where components hadn't fully updated.

chore: variable names

---

.github/workflows/terraform.yml
app/form-components/FormStageBox.tsx
app/jest/form.test.tsx

The tabs in the request create/edit window have data-testids but they change depending of how many environments are specced. So the preview tab can have `data-testid="stage-4` or `-5` or `-6`. This is a bit awkward to deal with.
The solution is to make fixed-name testids by setting them to the title of the tab. like this:
```typescript
data-testid={`stage-${kebabCase(title)}`}
``` 
Line 98 in `FormStageBox.tsx`

chore: Making test ids for the tabs less ephemeral by kebab casing

---

app/form-components/team-form/CreateTeamForm.tsx

When creating a new team, entering a team name larger than 255 characters causes a 422 error. (Shows up as 503 in screen message). The actual error message shows:
```json
{
"success": false,
"message": "value too long for type character varying(255)"
}
```
This fix sets `maxlength="255"` for the Team Name input field.

fix: set maximum length of team name to 255

---

app/components/TeamActionButtons.tsx

Adding 2 data-testid for team management purposes. They are on the edit and delete icons in the teams table.

feat: adding two testids for teams management

---

lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/shared/templates/create-github-bottom.html

fix for email format bug in outlook, outlook adds another empty \<li\> if there is no html element after a list, adding in an empty div at the end fixes it.

fix: outlook bug

---

app/layout/Layout.tsx

Application was still showing `<a href="mailto:Vardhman.Shankar@gov.bc.ca" title="SSO Team">` in Layout.tsx.
Changed the email address to the SSO Team email.

fix: remove old email and replace with sso team

---

app/components/CenteredModal.tsx
app/jest/my-dashboard/my-projects/integrationList.test.tsx
app/jest/my-dashboard/my-teams/integrations.test.tsx
app/jest/my-dashboard/my-teams/members.test.tsx
app/jest/ssoDashboard.test.tsx

With the current structure of the application, we end up with many duplicate testids.
This is because the modal dialogs are being used in multiple places and the testids are not unique.
This PR fixes that by adding a postfix to the testids that is unique to the component (basically the title of the dialog) that is using the modal dialog.
fix: ssoteam 1179 eliminate duplicate testids

fix: make testids unique

---

app/form-components/team-form/TeamMembersForm.tsx

The current validation when adding a new email always presents the same error message on failure.
Failure modes are:
* Email not there
* Email invalid
If either one is true the the message: **'Please enter an email'** is shown.
This fix will distinguish between the 2 error situations and in case of a invalid email it will show: **'Please enter a valid email'**

fix: improve member email validation

---

app/pages/_app.tsx

Setting the favicon to [/bootstrap-theme/dist/images/bcid-favicon-32x32.png](https://bcgov.github.io/bootstrap-theme/dist/images/bcid-favicon-32x32.png) because the way the application deals with its base URL causes issue with relative links.
So for the time being we can fix this, with the notion that there might be a future need to work on how the base path operates in the application.

fix: set the favicon to bootstrap theme

---

app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/jest/my-dashboard/my-teams/teamList.test.tsx
app/page-partials/my-dashboard/TeamInfoTabs/index.tsx

Added a validation so that user do not accidently add the admin email again when creating a new team. We already had the validation on duplicate team members, but we needed to validate the admin (first team member in the list) email as well.

fix: expand validation team members form

---

app/components/Carousel.tsx
app/components/Testimonial.tsx
app/hooks/useWindowDimensions.tsx
app/interfaces/Testimonial.ts
app/pages/index.tsx
app/utils/constants.ts

Add carousel for testimonials. As agreed we are hardcoding them right now, I made it an imported constant so it will be easy to switch to an API call later if we want.
When going over the mockup I realized some of the design was a bit unclear, e.g the testimonials have a title in the design but not in the spreadsheet. There was also a "Lorem Ipsum" top quote, not sure what the content was supposed to be. I still think it looks good though, image below of what is implemented:

feat: testimonials

---

.github/workflows/e2e-smoke-test.yaml

Adding a dependency on the completion of 'Build and Deploy GH Pages'

fix: e2e-smoke-test dependency

---

.github/workflows/e2e-smoke-test.yaml

Push trigger and workflow waits are mutually exclusive.

fix: push trigger

---

.github/workflows/e2e-smoke-test.yaml

Narrow down the running for just dev and only when terraform succeeds.

feat: fixes to run conditions for e2e

---

.dockerignore
app/package.json
app/pages/_app.tsx
docker-compose.yml
lambda/app/src/bceid-webservice-proxy/idir.ts
lambda/app/src/utils/constants.ts

Some small changes for the e2e test:
- Optional IDIR lookup bypass if CYPRESS_RUNNER env var is given. 
- Run the next build of the UI instead of the dev server, requires less resources
- Add optional chaining to the refresh token exp, was causing errors in the headless runner on logout

chore: cypress update

---

.github/workflows/e2e.yaml

Run a subset of the e2e test suite in our CI pipeline. I have altered a few tests on the fix/prereqs branch so that they can be run individually and still pass. We may need to add a new testsuite that is stateless to use in CI, but the current setup to run agains the docker compose and hit it with cypress is all setup now

chore: run e2e tests in ci pipeline

---

.github/workflows/e2e-smoke-test.yaml
.github/workflows/e2e.yaml

- only run e2e workflows when the frontend or backend change

chore: paths in action

---

app/form-components/FormTemplate.tsx
app/jest/form.test.tsx
app/jest/samples/integrations.ts
app/schemas/providers-gold.ts
app/utils/validate.ts
lambda/__tests__/03.requests-by-users.test.ts
lambda/__tests__/07.emails-for-user-requests.test.ts
lambda/__tests__/08.emails-for-team-requests.test.ts

This will cause an issue for clients who have triggered this bug previously. In production, there are only two clients who have done so (One is a test account of ours, the other is from a client).I think they can both be deleted (the client one has created another to replace it I believe, it is the same client who flagged this bug for us). Our form logic disables the public/confidential radios and the account type buttons once an integration is applied, so there is no good way to allow a self fix from the UI. If the client one cannot be deleted we will have to update the DB and keycloak client manually to allow it to be editable.

fix: disallow public service accounts

---

.github/workflows/e2e.yaml
app/components/CenteredModal.tsx
app/jest/ssoDashboard.test.tsx
app/pages/admin-dashboard.tsx
app/services/request.ts
docker-compose.yml
lambda/__tests__/03.requests-by-users.test.ts
lambda/__tests__/helpers/modules/integrations.ts
lambda/app/src/bceid-webservice-proxy/idir.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/routes.ts

Update the restore logic to allow admins to change ownership to a new idir email. This will be asked for unless the integration is owned by an existing team. I changed the e2e test to use `pull_request` trigger instead of `pull_request_target` so that a pr can update the test dependencies, otherwise it is using the target branch. For this run both will trigger but once merged it will just be the new one. The previous is failing because of an incorrect keycloak tag.

feat: restore integration

---

app/components/ActionButtons.tsx
app/components/InstallationPanel.tsx
app/components/TableNew.tsx
app/form-components/FormTemplate.tsx
app/form-components/team-form/CreateTeamForm.tsx
app/form-components/team-form/TeamMembersForm.tsx
app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
app/jest/my-dashboard/my-projects/assignUsersToRoles.test.tsx
app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
app/page-partials/my-dashboard/IntegrationList.tsx
app/page-partials/my-dashboard/Messages.tsx
app/page-partials/my-dashboard/RoleManagement/CreateRoleContent.tsx
app/page-partials/my-dashboard/RoleManagement/RoleEnvironment.tsx
app/page-partials/my-dashboard/ServiceAccountRoles.tsx
app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
app/page-partials/my-dashboard/UserRoles.tsx
app/pages/admin-dashboard.tsx
app/pages/admin-reports.tsx
app/services/axios.ts
app/services/report.ts

This removes the default rerouting to an error page from the axios interceptor so that general api error codes don't always push the user there. The bulk of the changes here are going through the existing AJAX requests and flashing our alert banner for ones that relied on the re-route previously.
I added a couple of quick fixes while going through the frontend:
- Update key to be correct
- Set some errors to more generic messages
- Clear out some form data for team members when the modal is cancelled

feat: client error handling update

---

lambda/__tests__/14.verifiable-credential.test.ts
lambda/app/src/controllers/requests.ts
lambda/shared/local.ts
lambda/shared/templates/create-integration-submitted/index.ts
lambda/shared/templates/delete-integration-submitted/index.ts
lambda/shared/templates/update-integration-submitted/index.ts

update email cases for digital credentials to only be CC the dc team when production is originally submitted or added

chore: update emails

---

app/components/ActionButtons.tsx
app/components/CenteredModal.tsx
app/components/DeleteModal.tsx
app/jest/my-dashboard/my-projects/integrationList.test.tsx
app/jest/my-dashboard/my-teams/integrations.test.tsx
app/jest/ssoDashboard.test.tsx
app/pages/admin-dashboard.tsx

- Adds input to type in project name before being allowed to delete
- Fixes css visibility issue with restore modal 
UI below:
Without name button disabled:
With name typed in allowed:

feat: confirm deletion

---

lambda/__tests__/11.remove-inactive-users.test.ts
lambda/app/src/controllers/user.ts

The non team integrations created by inactive IDIR users shall be assigned to SSO Team User and then archived without disabling them in the process.

fix: remove disable integration step before deletion

---

lambda/app/src/controllers/requests.ts

delete bcsc clients when disabling integration

chore: delete clients

---

app/components/RequestPreview.tsx
app/form-components/FieldReviewAndSubmit.tsx
app/form-components/FormTemplate.tsx
app/helpers/integration.ts
app/jest/ssoDashboard.test.tsx
app/page-partials/admin-dashboard/AdminRequestPanel.tsx
lambda/__tests__/06.email-templates.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/shared/templates/helpers.ts
lambda/shared/templates/index.ts
lambda/shared/templates/integration-detail.html

Adds the privacy zone name to the emails and admin dashboard display for BCSC integrations. I was going back and forth on just fetching it when mailing or saving the name to the database. Since it is just a display item and not used for any request logic I decided to add the extra fetch instead of migrating the db/updating the data model and rewriting the zone select widget.

chore: privacy zone name

---

lambda/__tests__/21.requests-validations.test.ts
lambda/app/src/controllers/requests.ts

- Allow updates to team and ownership for applied requests
- For applied requests, only allow submission not "draft edits"

fix: ownership updates

---

app/components/RequestPreview.tsx
app/form-components/FieldReviewAndSubmit.tsx
app/jest/ssoDashboard.test.tsx
app/page-partials/admin-dashboard/AdminRequestPanel.tsx
app/schemas/providers-gold.ts
lambda/__tests__/24.bcsc-api.test.ts
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/bc-services-card.ts

Store the display name for the privacy zone instead of the URI, and fetch the correct URI at create time.
There was also some logic in the frontend admin-panel to grab the display name, I took that out and the relevant test since it is directly on the integration now

fix: privacy zone uris

---

.tool-versions
Dockerfile
app/services/axios.ts
lambda/app/package.json
lambda/app/yarn.lock
lambda/jest.config.js
lambda/tsconfig.jest.json
localserver/bunfig.toml
localserver/package.json
localserver/reflect-metadata-import.ts

Bump keycloak lib to match our keycloak version, and fix local dev environment. The new keycloak-admin-client version's ESM syntax was not compatible with ts-node which we use to develop locally, so I switched it out to use bun. There are many alternatives, but note that anything built on top of esbuild (like `tsx`) does not support "emitDecoratorMetadata" in the tsconfig which we require. This is because [esbuild won't do type checking](https://esbuild.github.io/content-types/#typescript).
Bun seems like a great choice though, it's super fast on the hot reloading and is [committed to supporting cjs long term](https://bun.sh/blog/commonjs-is-not-going-away). Also has some out of the box features like automatic env file loading, hot reloading without nodemon as a requirement, and ts …

chore: bump keycloak library

---

lambda/app/src/keycloak/installation/oidc.ts

add information on the service account username to json payload for relevant client types

chore: svc acct username

---

app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
app/services/grafana.ts
lambda/app/src/keycloak/installation/oidc.ts
lambda/app/src/main.ts
lambda/app/src/routes.ts
lambda/css-api/src/routes.ts
lambda/css-api/src/swagger.js
localserver/express-server.ts
terraform/api-gateway.tf

Two improvements for large log downloads:
- Compression at the API Gateway for responses larger than 25KB
- Send the message for "all logs retrieved" or size limit reached in the header "x-message". This prevents having to parse out the JSON blob just to read the message on the client, so the logs blob can be attached to file download directly.
Also included the message in the css-api response, which has useful information if query params are incorrect, e.g malformed dates.

chore: large download

---

app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
lambda/__tests__/11.remove-inactive-users.test.ts
lambda/app/src/controllers/user.ts

- Check for undefined on progress event, some browsers are not reading in the Content-Length header for zipped responses
- skip the deletion emails if the integrations are archived

chore: deletion emails

---

lambda/jest.config.js
lambda/request-queue/src/db.ts
lambda/request-queue/src/main.ts
lambda/shared/sequelize/models/models.ts

Customizing the sequelize connection for the request queue. See [here](https://sequelize.org/docs/v6/other-topics/aws-lambda/#tldr) for reference on setting up sequelize and and lambda functions, they are recommending to avoid pooling across invocations.
I added this only for the request-queue lambda, since it runs in a single invocations every 5 minutes there aren't multiple containers in parallel creating connections. If using the same thing in the API lambda functions, we should first add [AWS RDS Proxy](https://aws.amazon.com/rds/proxy/) to make connections to the DB cheaper to establish, since they will have multiple running containers at once.

fix: sequalize connections

---

terraform/env-resources.tf_prod

Remove old module from terraform, in the env-resources.tf_prod file there is an s3 reference with the same bucket name I used for loki. This overrode some of its configuration on production deploy.
The bucket was being tracked in both sets of terraform state. I have removed this form the sso-requests state so that it no longer tracks it and won't try to remove it.

chore: old module

---

lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts

1. Only dev and test client names contain env suffix
2. jwks URI now includes `/auth`

feat: format client name and jwks uri for bcsc integrations

---

app/jest/form.test.tsx
app/schemas-ui/ui-gold.ts
lambda/__tests__/21.requests-validations.test.ts
lambda/__tests__/24.bcsc-api.test.ts
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/keycloak/integration.ts
lambda/app/src/queries/bcsc-client.ts

BC Services Card Updates:
1. Allow privacy zone update before approval
2. Allow removal of bcsc idp before approval

feat: allow privacy zone updates for bcsc

---

README.md
terraform/provider.tf
terraform/roles.tf

scope down the terraform service account permission. Uses the same setup as sso-dashboard with a different boundary:
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "Allow",
"Effect": "Allow",
"Action": [
"s3:*",
"apigateway:*",
"lambda:*",
"ecs:*",
"ec2:*",
"elasticloadbalancing:*",
"cloudwatch:*",
"dynamodb:*",
"rds:*",
"acm:*",
"events:*",
"secretsmanager:GetSecretValue",
"elasticfilesystem:*"
],
"Resource": "*"
}
]
}
```

chore: permissions

---

lambda/app/src/controllers/requests.ts

Disabling client name updates until BCSC side could apply a patch to their DCR API to allow such updates.

fix: client name updates at bcsc disabled

---

lambda/__tests__/20.bcsc.test.ts
lambda/app/src/bcsc/client.ts
lambda/app/src/controllers/requests.ts
lambda/app/src/queries/request.ts

1. The jwks_uri parameter is required only if encryption was enabled so removing it for now. 
2. The BCSC API is called only when creating a new or updating BCSC specific fields for existing one.

feat: disable jwks_uri and update bcsc api conditionally

---

app/jest/form.test.tsx
app/schemas/providers-gold.ts
lambda/__tests__/21.requests-validations.test.ts
lambda/app/src/controllers/requests.ts

allow admins to still use on-prem idir

feat: admin idir access

---

.github/workflows/deploy-gh-pages-maintenance.yml
.github/workflows/deploy-gh-pages.yml
.github/workflows/k6-tests.yml
.github/workflows/terraform.yml
.github/workflows/test.yml
.tool-versions
app/next.config.js
app/package.json
docker-compose.yml

- Update ubuntu runner to 24 in applicable github actions
- Update nextjs build syntax for the 14 migration, exporting for static builds has changed
- Match localdev postgres version to deployed version

chore: version updates

---

app/form-components/FormTemplate.tsx
app/form-components/widgets/TooltipCheckboxesWidget.tsx
app/form-components/widgets/TooltipIDPCheckboxesWidget.tsx
app/next.config.js
app/schemas-ui/ui-gold.ts

Fix bug with IDP selection to apply filtering again. With react 18 the child widget stopped re-rendering when the global handler applied idp filtering logic, so this moves it into the IDP selection widget.
Also removed rewrites from next config, this has been deprecated now and we set an env variable for the API base url so it is not needed

chore: idp selection

---

.github/workflows/terraform.yml
lambda/app/src/bcsc/client.ts
terraform/variables.tf

add env var for the bcsc signing algorithm. Setting to PS256 in sandbox only, and leaving the old RS256 in test/prod, since it is only avaiable in SIT right now

chore: signing alg

---

lambda/__tests__/03.requests-by-users.test.ts
lambda/__tests__/helpers/fixtures.ts
lambda/app/src/queries/request.ts

When an integration is in draft, users can toggle on "uses team" and leave before selecting a team from the dropdown. This is fine since they cannot submit for creation until choosing one, but had a bug where it would not show in the dashboard list anymore. This ticket updates the DB select to cover that case

fix: integration fetch

---

app/components/ActionButtons.tsx
app/helpers/permissions.ts
app/jest/my-dashboard/my-projects/integrationList.test.tsx

allow draft deletion for partial team integrations (e.g. user switched to team but has not selected one yet)

chore: delete enabling

---

app/components/InstallationPanel.tsx

remove hardcoded height from grid column, breaks overflow on small screens.

chore: hardcoded height

---

app/pages/_app.tsx
lambda/__tests__/11.remove-inactive-users.test.ts
lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
lambda/app/src/controllers/user.ts
lambda/shared/enums.ts
lambda/shared/sequelize/models/UserTeam.ts
lambda/shared/templates/delete-inactive-idir-users/delete-inactive-idir-users.html
lambda/shared/templates/index.ts
lambda/shared/templates/orphan-integration/orphan-integration.html
lambda/shared/templates/remove-inactive-idir-user-from-team/index.ts
lambda/shared/templates/remove-inactive-idir-user-from-team/remove-inactive-idir-user-from-team.html

Updated the user deletion emailing, separating out the messages:
- Sends the "user with role deleted" message separately from team memberships change
- Emails all integration owners when a user with client-roles on it is removed in any environment
- For users removed from production, moves any orphaned integrations to our team and notifies us
- Sends an email to all team-admins if any team member is deleted
I updated the unit tests checking for one email, since they are separated now. Added new tests for the different email cases

chore: deleted user emails

---

.github/workflows/e2e-keycloak.yaml
app/cypress.config.ts
app/cypress/appActions/Navigation.ts
app/cypress/e2e/external/idpstopper-010-test7-8.cy.ts
app/cypress/e2e/external/idpstopper-020-test11.cy.ts
app/cypress/e2e/external/idpstopper-050-login-page-name-capitalization.cy.ts
app/cypress/e2e/external/search-users.cy.ts
app/cypress/e2e/external/sso-020-sessions.cy.ts
app/cypress/pageObjects/playgroundPage.ts
app/cypress/support/commands.ts
docker-compose.yml
local/terraform/main.tf

Update e2e tests to use new url:
- Un-comment videos in CI, they only upload on test failure and are almost always required for debugging
- Update URLs in CI
- Update tests hitting playground-app to keep integration details, switching to a different domain on github pages was losing the integration ID
- Remove cy.origin when going to loginproxy, since on the same domain now
- Update to recent keycloak image in CI test

chore: update e2e tests

---

.github/workflows/k6-tests.yml
.github/workflows/test.yml
api/src/server.ts

- update swagger to the old location
- Update apt, was trying to find old mirrors that 404

chore: swagger url

---

.github/workflows/publish-image.yaml
app/.env.example
app/jest-api/07.emails-for-user-requests.test.ts
app/jest-api/12.submit-survey.test.ts
app/jest-api/jest.setup.js
app/shared/local.ts
app/shared/templates/create-integration-applied/index.ts
app/shared/templates/create-integration-submitted/index.ts
app/shared/templates/create-otp-bottom.html
app/shared/templates/delete-integration-submitted/index.ts
app/shared/templates/update-integration-submitted/index.ts
helm/templates/deployment.yaml
helm/templates/secret.yaml

Update email CC and BCC list for OTP integrations (create,delete,update). Adding olenas direct email to BCC was a requirement. I didn't want to commit that in code, so changed the email addresses to an env var. Instead of making 8 vars for each env I set it as the JSON structure that is in the .env.example

chore: otp emails

---

.github/workflows/publish-image.yaml
api/src/services/keycloak-service.ts
api/src/tests/keycloak-service.test.ts

The `refreshing` flag was not being reset to `false` on error, leading to the access token always being returned. This caused very flaky behaviour where tokens would sporadically be valid due to the following flow:
1. Token refresh fails, `refreshing` flag gets stuck as `true`
2. Follow up calls instantly return the current access token since `refreshing` is `true`
3. Only after the refresh token expires (30 minutes) does the code go into the else block and get a new set of tokens
4. Since the `refreshing` flag is still stuck on `true`, it returns the new access token until the new refresh token expires again. This resulted in successful requests for 5 minutes (access token lifespan) and failed requests for the remaining 25 minutes of the refresh token's lifespan, on repeat.
It will now …

fix: token refresh

---

api/package.json
api/src/services/keycloak-service.ts
api/src/tests/keycloak-service.test.ts

The CSS API tokens become invalidated on a full keycloak restart, and will return 401's until they expire and the API resets them. This adds logic to the axios interceptor to clear the cache on a 401 and retry once. In order to test the interceptor I added the axios-mock-adapter lib

chore: token cache clear
